apiVersion: batch/v1
kind: Job
metadata:
  name: my-job-{{ .Values.index }}
  annotations:
    # https://argo-cd.readthedocs.io/en/stable/user-guide/resource_hooks/#usage
    argocd.argoproj.io/hook: PreSync
    # https://argo-cd.readthedocs.io/en/stable/user-guide/resource_hooks/#hook-deletion-policies
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      containers:
        - name: migrate
          image: "busybox:1.28"
          command: ["/bin/sleep", "3"]
      restartPolicy: Never
---
