{{- range $i := until 8 }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: ns-{{ $i }}
---
  {{- range $j := until 8 }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-{{ $j }}
  namespace: ns-{{ $i }}
spec:
  project: default
  source:
    repoURL: https://github.com/SJrX/argocd-bug
    path: ./presync-hook
    targetRevision: HEAD
    helm:
      parameters:
        - name: index
          value: "{{ $j }}"
  destination:
    server: https://kubernetes.default.svc
    namespace: ns-{{ $i }}
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true


---
{{- end }}
{{- end }}